### ISSUE TITLE
Install this extension on the customers staging website

### ISSUE THREAD

**Issue by jonathonbyrdziak** [merchantprotocol/M1-warehouse-dimensional-shipping#1]
Host: http://cos-exts.transformagency.com 

BACKEND / ADMIN

Username: admin
Password: FealtyStyeMutesGlumly11

FTP LOGINS ARE:

Username: devs@cos-exts.transformagency.com
 Password: FealtyStyeMutesGlumly11

**Comment by alancarvalho** [comment]
Finish.

Test product: http://cos-exts.transformagency.com/swiss-movement-sports-watch.html
